/*
 * Interests.java
 *
 * Created on __DATE__, __TIME__
 */

package FB;

import java.util.List;

import org.hibernate.Transaction;

/**
 *
 * @author  __USER__
 */
public class Interests extends javax.swing.JFrame {

	/** Creates new form Interests */
	public Interests() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jCheckBox1 = new javax.swing.JCheckBox();
		jLabel1 = new javax.swing.JLabel();
		jCheckBox2 = new javax.swing.JCheckBox();
		jCheckBox3 = new javax.swing.JCheckBox();
		jCheckBox4 = new javax.swing.JCheckBox();
		jCheckBox5 = new javax.swing.JCheckBox();
		jCheckBox6 = new javax.swing.JCheckBox();
		jCheckBox7 = new javax.swing.JCheckBox();
		jCheckBox8 = new javax.swing.JCheckBox();
		jCheckBox9 = new javax.swing.JCheckBox();
		jButton1 = new javax.swing.JButton();

		jCheckBox1.setText("Sports");
		jCheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jCheckBox1MouseReleased(evt);
			}
		});
		jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox1ActionPerformed(evt);
			}
		});

		jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 24));
		jLabel1.setText("Interests:");

		jCheckBox2.setText("Technology");
		jCheckBox2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jCheckBox2MouseReleased(evt);
			}
		});
		jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox2ActionPerformed(evt);
			}
		});

		jCheckBox3.setText("Science");
		jCheckBox3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jCheckBox3MouseReleased(evt);
			}
		});
		jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox3ActionPerformed(evt);
			}
		});

		jCheckBox4.setText("Games");
		jCheckBox4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jCheckBox4MouseReleased(evt);
			}
		});
		jCheckBox4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox4ActionPerformed(evt);
			}
		});

		jCheckBox5.setText("Movies");
		jCheckBox5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jCheckBox5MouseReleased(evt);
			}
		});
		jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox5ActionPerformed(evt);
			}
		});

		jCheckBox6.setText("Art");
		jCheckBox6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jCheckBox6MouseReleased(evt);
			}
		});
		jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox6ActionPerformed(evt);
			}
		});

		jCheckBox7.setText("Family");
		jCheckBox7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jCheckBox7MouseReleased(evt);
			}
		});
		jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox7ActionPerformed(evt);
			}
		});

		jCheckBox8.setText("Music");
		jCheckBox8.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jCheckBox8MouseReleased(evt);
			}
		});
		jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox8ActionPerformed(evt);
			}
		});

		jCheckBox9.setText("Business");
		jCheckBox9.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jCheckBox9MouseReleased(evt);
			}
		});
		jCheckBox9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox9ActionPerformed(evt);
			}
		});

		jButton1.setText("Update");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton1MouseReleased(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout.createSequentialGroup().addGap(168, 168,
										168).addComponent(jLabel1)
										.addContainerGap(214, Short.MAX_VALUE))
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(49, 49, 49)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jCheckBox1)
														.addComponent(
																jCheckBox4)
														.addComponent(
																jCheckBox7))
										.addGap(108, 108, 108)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addContainerGap())
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jCheckBox2)
																						.addComponent(
																								jCheckBox5)
																						.addComponent(
																								jCheckBox8))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				71,
																				Short.MAX_VALUE)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jCheckBox3)
																						.addComponent(
																								jCheckBox6)
																						.addComponent(
																								jCheckBox9))
																		.addGap(
																				82,
																				82,
																				82)))));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				25,
																				25,
																				25)
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				44,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jCheckBox2)
																						.addComponent(
																								jCheckBox3)))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				72,
																				72,
																				72)
																		.addComponent(
																				jCheckBox1)))
										.addGap(26, 26, 26)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBox4)
														.addComponent(
																jCheckBox5)
														.addComponent(
																jCheckBox6))
										.addGap(26, 26, 26)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jCheckBox9)
														.addComponent(
																jCheckBox8)
														.addComponent(
																jCheckBox7))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												49, Short.MAX_VALUE)
										.addComponent(jButton1).addGap(28, 28,
												28)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {
		this.setVisible(false);
	}

	public javax.swing.JButton getjButton1() {
		return jButton1;
	}

	public void setjButton1(javax.swing.JButton jButton1) {
		this.jButton1 = jButton1;
	}

	public javax.swing.JCheckBox getjCheckBox1() {
		return jCheckBox1;
	}

	public void setjCheckBox1(javax.swing.JCheckBox jCheckBox1) {
		this.jCheckBox1 = jCheckBox1;
	}

	public javax.swing.JCheckBox getjCheckBox2() {
		return jCheckBox2;
	}

	public void setjCheckBox2(javax.swing.JCheckBox jCheckBox2) {
		this.jCheckBox2 = jCheckBox2;
	}

	public javax.swing.JCheckBox getjCheckBox3() {
		return jCheckBox3;
	}

	public void setjCheckBox3(javax.swing.JCheckBox jCheckBox3) {
		this.jCheckBox3 = jCheckBox3;
	}

	public javax.swing.JCheckBox getjCheckBox4() {
		return jCheckBox4;
	}

	public void setjCheckBox4(javax.swing.JCheckBox jCheckBox4) {
		this.jCheckBox4 = jCheckBox4;
	}

	public javax.swing.JCheckBox getjCheckBox5() {
		return jCheckBox5;
	}

	public void setjCheckBox5(javax.swing.JCheckBox jCheckBox5) {
		this.jCheckBox5 = jCheckBox5;
	}

	public javax.swing.JCheckBox getjCheckBox6() {
		return jCheckBox6;
	}

	public void setjCheckBox6(javax.swing.JCheckBox jCheckBox6) {
		this.jCheckBox6 = jCheckBox6;
	}

	public javax.swing.JCheckBox getjCheckBox7() {
		return jCheckBox7;
	}

	public void setjCheckBox7(javax.swing.JCheckBox jCheckBox7) {
		this.jCheckBox7 = jCheckBox7;
	}

	public javax.swing.JCheckBox getjCheckBox8() {
		return jCheckBox8;
	}

	public void setjCheckBox8(javax.swing.JCheckBox jCheckBox8) {
		this.jCheckBox8 = jCheckBox8;
	}

	public javax.swing.JCheckBox getjCheckBox9() {
		return jCheckBox9;
	}

	public void setjCheckBox9(javax.swing.JCheckBox jCheckBox9) {
		this.jCheckBox9 = jCheckBox9;
	}

	private void jCheckBox9MouseReleased(java.awt.event.MouseEvent evt) {
		Interests newi = new Interests();
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile ma = dao.findById(FirstPage.id);
		int i;
		for (i = 0; i < ma.getInterests().size(); i++) 
			if(ma.getInterests().get(i).getName().equals(newi.getjCheckBox9().getText())){
				dx.commit();
				dao.getSession().close();
				RemoveInterest(FirstPage.id, "Business");
				return;
	}
		dx.commit();
		dao.getSession().close();
		AddInterest(FirstPage.id, "Business");
	}

	private void jCheckBox8MouseReleased(java.awt.event.MouseEvent evt) {
		Interests newi = new Interests();
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile ma = dao.findById(FirstPage.id);
		int i;
		for (i = 0; i < ma.getInterests().size(); i++) 
			if(ma.getInterests().get(i).getName().equals(newi.getjCheckBox8().getText())){
				dx.commit();
				dao.getSession().close();
				RemoveInterest(FirstPage.id, "Music");
				return;
	}
		dx.commit();
		dao.getSession().close();
		AddInterest(FirstPage.id, "Music");
	}

	private void jCheckBox7MouseReleased(java.awt.event.MouseEvent evt) {
		Interests newi = new Interests();
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile ma = dao.findById(FirstPage.id);
		int i;
		for (i = 0; i < ma.getInterests().size(); i++) 
			if(ma.getInterests().get(i).getName().equals(newi.getjCheckBox7().getText())){
				dx.commit();
				dao.getSession().close();
				RemoveInterest(FirstPage.id, "Family");
				return;
	}
		dx.commit();
		dao.getSession().close();
		AddInterest(FirstPage.id, "Family");
	}

	private void jCheckBox6MouseReleased(java.awt.event.MouseEvent evt) {
		Interests newi = new Interests();
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile ma = dao.findById(FirstPage.id);
		int i;
		for (i = 0; i < ma.getInterests().size(); i++) 
			if(ma.getInterests().get(i).getName().equals(newi.getjCheckBox6().getText())){
				dx.commit();
				dao.getSession().close();
				RemoveInterest(FirstPage.id, "Art");
				return;
	}
		dx.commit();
		dao.getSession().close();
		AddInterest(FirstPage.id, "Art");
	}

	private void jCheckBox5MouseReleased(java.awt.event.MouseEvent evt) {
		Interests newi = new Interests();
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile ma = dao.findById(FirstPage.id);
		int i;
		for (i = 0; i < ma.getInterests().size(); i++) 
			if(ma.getInterests().get(i).getName().equals(newi.getjCheckBox5().getText())){
				dx.commit();
				dao.getSession().close();
				RemoveInterest(FirstPage.id, "Movies");
				return;
	}
		dx.commit();
		dao.getSession().close();
		AddInterest(FirstPage.id, "Movies");
	}

	private void jCheckBox4MouseReleased(java.awt.event.MouseEvent evt) {
		Interests newi = new Interests();
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile ma = dao.findById(FirstPage.id);
		int i;
		for (i = 0; i < ma.getInterests().size(); i++) 
			if(ma.getInterests().get(i).getName().equals(newi.getjCheckBox4().getText())){
				dx.commit();
				dao.getSession().close();
				RemoveInterest(FirstPage.id, "Games");
				return;
	}
		dx.commit();
		dao.getSession().close();
		AddInterest(FirstPage.id, "Games");
	}

	private void jCheckBox3MouseReleased(java.awt.event.MouseEvent evt) {
		Interests newi = new Interests();
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile ma = dao.findById(FirstPage.id);
		int i;
		for (i = 0; i < ma.getInterests().size(); i++) 
			if(ma.getInterests().get(i).getName().equals(newi.getjCheckBox3().getText())){
				dx.commit();
				dao.getSession().close();
				RemoveInterest(FirstPage.id, "Science");
				return;
	}
		dx.commit();
		dao.getSession().close();
		AddInterest(FirstPage.id, "Science");
	}

	private void jCheckBox1MouseReleased(java.awt.event.MouseEvent evt) {
		Interests newi = new Interests();
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile ma = dao.findById(FirstPage.id);
		int i;
		for (i = 0; i < ma.getInterests().size(); i++) 
			if(ma.getInterests().get(i).getName().equals(newi.getjCheckBox1().getText())){
				dx.commit();
				dao.getSession().close();
				RemoveInterest(FirstPage.id, "Sports");
				return;
	}
		dx.commit();
		dao.getSession().close();
		AddInterest(FirstPage.id, "Sports");
	}

	private void jCheckBox2MouseReleased(java.awt.event.MouseEvent evt) {
		Interests newi = new Interests();
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile ma = dao.findById(FirstPage.id);
		int i;
		for (i = 0; i < ma.getInterests().size(); i++) 
			if(ma.getInterests().get(i).getName().equals(newi.getjCheckBox2().getText())){
				dx.commit();
				dao.getSession().close();
				RemoveInterest(FirstPage.id, "Technology");
				return;
	}
		dx.commit();
		dao.getSession().close();
		
		AddInterest(FirstPage.id, "Technology");

	}

	static void AddInterest(Integer profileid, String interestname) {
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile a = dao.findById(profileid);

		List<Interest> newpis = a.getInterests();
		Interest newi = new Interest();
		newi.setName(interestname);

		newpis.add(newi);

		dao.attachClean(a);
		dx.commit();
		dao.getSession().close();

	}
	static void RemoveInterest(Integer profileid, String interestname) {
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile a = dao.findById(profileid);
	//	Interest found;
		int i;
		List<Interest> newpis = a.getInterests();
		for(i=0;i<newpis.size();i++)
			if(newpis.get(i).getName().equals(interestname))
				newpis.remove(i);
		
		dao.attachClean(a);
		dx.commit();
		dao.getSession().close();

	}
	
	

	private void jCheckBox9ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Interests().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JCheckBox jCheckBox1;
	private javax.swing.JCheckBox jCheckBox2;
	private javax.swing.JCheckBox jCheckBox3;
	private javax.swing.JCheckBox jCheckBox4;
	private javax.swing.JCheckBox jCheckBox5;
	private javax.swing.JCheckBox jCheckBox6;
	private javax.swing.JCheckBox jCheckBox7;
	private javax.swing.JCheckBox jCheckBox8;
	private javax.swing.JCheckBox jCheckBox9;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables

}