/*
 * ShowPoeple.java
 *
 * Created on __DATE__, __TIME__
 */

package FB;

import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.List;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

import org.hibernate.Transaction;

/**
 *
 * @author  __USER__
 */
public class ShowPoeple extends javax.swing.JFrame {

	/** Creates new form ShowPoeple */
	public ShowPoeple() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel3 = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jLabel4 = new javax.swing.JLabel();
		jLabel5 = new javax.swing.JLabel();
		jButton2 = new javax.swing.JButton();
		jLabel6 = new javax.swing.JLabel();
		jLabel7 = new javax.swing.JLabel();
		jButton3 = new javax.swing.JButton();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jButton4 = new javax.swing.JButton();
		jLabel10 = new javax.swing.JLabel();
		jButton7 = new javax.swing.JButton();
		jButton6 = new javax.swing.JButton();
		jLabel11 = new javax.swing.JLabel();
		jButton5 = new javax.swing.JButton();
		jLabel12 = new javax.swing.JLabel();
		jLabel13 = new javax.swing.JLabel();
		jLabel14 = new javax.swing.JLabel();
		jLabel15 = new javax.swing.JLabel();
		jLabel16 = new javax.swing.JLabel();

		jLabel3.setText("Results:");

		jButton1.setText("Add As a Friend");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton1MouseReleased(evt);
			}
		});

		jButton2.setText("Add as a Friend");
		jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton2MouseReleased(evt);
			}
		});

		jButton3.setText("Add as a Friend");
		jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton3MouseReleased(evt);
			}
		});

		jButton4.setText("Add as a Frind");
		jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton4MouseReleased(evt);
			}
		});

		jButton7.setText("Up");
		jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton7MouseReleased(evt);
			}
		});

		jButton6.setText("Down");
		jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton6MouseReleased(evt);
			}
		});

		jButton5.setText("Add as a Friend");
		jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jButton5MouseReleased(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				45,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				103,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel12)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				158,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel8,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				45,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel9,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				103,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel15)
																		.addGap(
																				5,
																				5,
																				5)
																		.addComponent(
																				jButton4,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				158,
																				Short.MAX_VALUE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel10,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				45,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jButton7,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												63,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																										.addComponent(
																												jButton6))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel11,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												103,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel16)
																										.addGap(
																												5,
																												5,
																												5)
																										.addComponent(
																												jButton5,
																												javax.swing.GroupLayout.DEFAULT_SIZE,
																												158,
																												Short.MAX_VALUE))))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel6,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												45,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel7,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												103,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel14))
																						.addGroup(
																								layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel4,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												45,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jLabel5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												103,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGap(
																				5,
																				5,
																				5)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								layout
																										.createSequentialGroup()
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																												158,
																												Short.MAX_VALUE)
																										.addComponent(
																												jLabel13))
																						.addComponent(
																								jButton2,
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								158,
																								Short.MAX_VALUE)
																						.addComponent(
																								jButton3,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								158,
																								Short.MAX_VALUE))))
										.addContainerGap()).addGroup(
								layout.createSequentialGroup().addGap(135, 135,
										135).addComponent(jLabel3,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										64, Short.MAX_VALUE).addGap(150, 150,
										150)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(jLabel3)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																47,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel2)
														.addComponent(jButton1)
														.addComponent(jLabel12))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																47,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel5)
														.addComponent(jLabel13)
														.addComponent(jButton2))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																47,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel7)
														.addComponent(jButton3)
														.addComponent(jLabel14))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel8,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																47,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel9)
														.addComponent(jButton4)
														.addComponent(jLabel15))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jLabel10,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																47,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel11)
														.addComponent(jButton5)
														.addComponent(jLabel16))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jButton7)
														.addComponent(jButton6))));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton5MouseReleased(java.awt.event.MouseEvent evt) {
		/*	ProfilePage fpg = new ProfilePage();
			fpg.getjButton2().setVisible(false);
			ProfileDAO dao = new ProfileDAO();
			Transaction dx = dao.getSession().beginTransaction();
			Profile b = dao.findById(Integer.parseInt(jLabel10.getText()));
			fpg.getjLabel2().setText(b.getFirstName());
			fpg.getjLabel3().setText(b.getLastName());
			current = FirstPage.id;
			FirstPage.id = b.getId();

			fpg.setVisible(true); */

		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		//	Profile b = dao.findById(Integer.parseInt(jLabel1.getText()));
		AddFriend(FirstPage.id, Integer.parseInt(jLabel10.getText()));
		System.out.println("Added!");
	}

	private void jButton6MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton7MouseReleased(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
	}

	private void jButton4MouseReleased(java.awt.event.MouseEvent evt) {
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		//	Profile b = dao.findById(Integer.parseInt(jLabel1.getText()));
		AddFriend(FirstPage.id, Integer.parseInt(jLabel8.getText()));
		System.out.println("Added!");
	}

	private void jButton3MouseReleased(java.awt.event.MouseEvent evt) {
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		//	Profile b = dao.findById(Integer.parseInt(jLabel1.getText()));
		AddFriend(FirstPage.id, Integer.parseInt(jLabel6.getText()));
		this.jLabel14.setText("Added!");
		this.jButton3.setVisible(false);
		System.out.println("Added!");
	}

	private void jButton2MouseReleased(java.awt.event.MouseEvent evt) {
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		//	Profile b = dao.findById(Integer.parseInt(jLabel1.getText()));
		AddFriend(FirstPage.id, Integer.parseInt(jLabel4.getText()));
		this.jLabel13.setText("Added!");
		this.jButton2.setVisible(false);
		System.out.println("Added!");
	}

	private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {
		//	ProfilePage fpg = new ProfilePage();
		//	fpg.getjButton2().setVisible(false);
		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		//	Profile b = dao.findById(Integer.parseInt(jLabel1.getText()));
		AddFriend(FirstPage.id, Integer.parseInt(jLabel1.getText()));
		this.jLabel12.setText("Added!");
		this.jButton1.setVisible(false);
		//	System.out.println("Added!");

	}

	public javax.swing.JLabel getjLabel12() {
		return jLabel12;
	}

	public void setjLabel12(javax.swing.JLabel jLabel12) {
		this.jLabel12 = jLabel12;
	}

	public javax.swing.JLabel getjLabel13() {
		return jLabel13;
	}

	public void setjLabel13(javax.swing.JLabel jLabel13) {
		this.jLabel13 = jLabel13;
	}

	public javax.swing.JLabel getjLabel14() {
		return jLabel14;
	}

	public void setjLabel14(javax.swing.JLabel jLabel14) {
		this.jLabel14 = jLabel14;
	}

	public javax.swing.JLabel getjLabel15() {
		return jLabel15;
	}

	public void setjLabel15(javax.swing.JLabel jLabel15) {
		this.jLabel15 = jLabel15;
	}

	public javax.swing.JLabel getjLabel16() {
		return jLabel16;
	}

	public void setjLabel16(javax.swing.JLabel jLabel16) {
		this.jLabel16 = jLabel16;
	}

	static void AddFriend(Integer id, Integer Friendid) {

		ProfileDAO dao = new ProfileDAO();
		Transaction dx = dao.getSession().beginTransaction();
		Profile a = dao.findById(id);

		List<Friend> newfs = a.getFriends();
		Friend newf = new Friend();
		newf.setFriendId(Friendid);
		newfs.add(newf);

		dao.attachClean(a);
		dx.commit();
		dao.getSession().close();

	}

	static void ShowPeople(List<Profile> foundf, FriendsPage fp, Integer frid)
			throws IOException {

		int i;
		int j;
		for (i = foundf.size() - 1 - frid, j = 0; i >= 0 && j < 5; i--, j++) {
			if (j == 0) {
				Profile c = foundf.get(i);//dao.findById(a.getFriends().get(i).getFriendId());
				fp.getjLabel2().setText(
						c.getFirstName() + " " + c.getLastName());
				fp.getjLabel1().setText(c.getId().toString());
				ImageIcon ia = new ImageIcon();
				Image img = ImageIO.read(new File(c.getPicture()));
				Image ib = img.getScaledInstance(50, 50, 50);
				ia.setImage(ib);
				fp.getjLabel1().setIcon(ia);

			}
			if (j == 1) {
				Profile c = foundf.get(i);// dao.findById(a.getFriends().get(i).getFriendId());
				fp.getjLabel5().setText(
						c.getFirstName() + " " + c.getLastName());
				fp.getjLabel4().setText(c.getId().toString());
				ImageIcon ia = new ImageIcon();
				Image img = ImageIO.read(new File(c.getPicture()));
				Image ib = img.getScaledInstance(50, 50, 50);
				ia.setImage(ib);
				fp.getjLabel4().setIcon(ia);
			}
			if (j == 2) {
				Profile c = foundf.get(i);//dao.findById(a.getFriends().get(i).getFriendId());
				fp.getjLabel7().setText(
						c.getFirstName() + " " + c.getLastName());
				fp.getjLabel6().setText(c.getId().toString());
				ImageIcon ia = new ImageIcon();
				Image img = ImageIO.read(new File(c.getPicture()));
				Image ib = img.getScaledInstance(50, 50, 50);
				ia.setImage(ib);
				fp.getjLabel6().setIcon(ia);
			}
			if (j == 3) {
				Profile c = foundf.get(i);//dao.findById(a.getFriends().get(i).getFriendId());
				fp.getjLabel9().setText(
						c.getFirstName() + " " + c.getLastName());
				fp.getjLabel8().setText(c.getId().toString());
				ImageIcon ia = new ImageIcon();
				Image img = ImageIO.read(new File(c.getPicture()));
				Image ib = img.getScaledInstance(50, 50, 50);
				ia.setImage(ib);
				fp.getjLabel8().setIcon(ia);
			}
			if (j == 4) {
				Profile c = foundf.get(i);//dao.findById(a.getFriends().get(i).getFriendId());
				fp.getjLabel11().setText(
						c.getFirstName() + " " + c.getLastName());
				fp.getjLabel10().setText(c.getId().toString());
				ImageIcon ia = new ImageIcon();
				Image img = ImageIO.read(new File(c.getPicture()));
				Image ib = img.getScaledInstance(50, 50, 50);
				ia.setImage(ib);
				fp.getjLabel10().setIcon(ia);
			}

		}

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ShowPoeple().setVisible(true);
			}
		});
	}

	public javax.swing.JLabel getjLabel1() {
		return jLabel1;
	}

	public void setjLabel1(javax.swing.JLabel jLabel1) {
		this.jLabel1 = jLabel1;
	}

	public javax.swing.JLabel getjLabel10() {
		return jLabel10;
	}

	public void setjLabel10(javax.swing.JLabel jLabel10) {
		this.jLabel10 = jLabel10;
	}

	public javax.swing.JLabel getjLabel11() {
		return jLabel11;
	}

	public void setjLabel11(javax.swing.JLabel jLabel11) {
		this.jLabel11 = jLabel11;
	}

	public javax.swing.JLabel getjLabel2() {
		return jLabel2;
	}

	public void setjLabel2(javax.swing.JLabel jLabel2) {
		this.jLabel2 = jLabel2;
	}

	public javax.swing.JLabel getjLabel3() {
		return jLabel3;
	}

	public void setjLabel3(javax.swing.JLabel jLabel3) {
		this.jLabel3 = jLabel3;
	}

	public javax.swing.JLabel getjLabel4() {
		return jLabel4;
	}

	public void setjLabel4(javax.swing.JLabel jLabel4) {
		this.jLabel4 = jLabel4;
	}

	public javax.swing.JLabel getjLabel5() {
		return jLabel5;
	}

	public void setjLabel5(javax.swing.JLabel jLabel5) {
		this.jLabel5 = jLabel5;
	}

	public javax.swing.JLabel getjLabel6() {
		return jLabel6;
	}

	public void setjLabel6(javax.swing.JLabel jLabel6) {
		this.jLabel6 = jLabel6;
	}

	public javax.swing.JLabel getjLabel7() {
		return jLabel7;
	}

	public void setjLabel7(javax.swing.JLabel jLabel7) {
		this.jLabel7 = jLabel7;
	}

	public javax.swing.JLabel getjLabel8() {
		return jLabel8;
	}

	public void setjLabel8(javax.swing.JLabel jLabel8) {
		this.jLabel8 = jLabel8;
	}

	public javax.swing.JLabel getjLabel9() {
		return jLabel9;
	}

	public void setjLabel9(javax.swing.JLabel jLabel9) {
		this.jLabel9 = jLabel9;
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton jButton5;
	private javax.swing.JButton jButton6;
	private javax.swing.JButton jButton7;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel jLabel13;
	private javax.swing.JLabel jLabel14;
	private javax.swing.JLabel jLabel15;
	private javax.swing.JLabel jLabel16;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	// End of variables declaration//GEN-END:variables

}